// @generated by `ccaudit refresh-prices --emit-table src/source/price_table.rs`.
// Do not edit by hand — rerun that command instead.
//
// Anthropic rates from LiteLLM, per million tokens. The offline
// fallback: a user who ran `refresh-prices` gets their newer copy
// first, and a model in neither is priced at zero and reported.
//
// Sorted by key — `claude_code::builtin_price` binary-searches it.

use super::Pricing;

#[rustfmt::skip]
pub static BUILTIN: &[(&str, Pricing)] = &[
    ("claude-3-7-sonnet-20250219", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-3-haiku-20240307", Pricing { input: 0.25, output: 1.25, cache_write: 0.3, cache_write_1h: 0.5, cache_read: 0.03 }),
    ("claude-3-opus-20240229", Pricing { input: 15.0, output: 75.0, cache_write: 18.75, cache_write_1h: 30.0, cache_read: 1.5 }),
    ("claude-4-opus-20250514", Pricing { input: 15.0, output: 75.0, cache_write: 18.75, cache_write_1h: 18.75, cache_read: 1.5 }),
    ("claude-4-sonnet-20250514", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 3.75, cache_read: 0.3 }),
    ("claude-fable-5", Pricing { input: 10.0, output: 50.0, cache_write: 12.5, cache_write_1h: 20.0, cache_read: 1.0 }),
    ("claude-haiku-4-5", Pricing { input: 1.0, output: 5.0, cache_write: 1.25, cache_write_1h: 2.0, cache_read: 0.1 }),
    ("claude-haiku-4-5-20251001", Pricing { input: 1.0, output: 5.0, cache_write: 1.25, cache_write_1h: 2.0, cache_read: 0.1 }),
    ("claude-opus-4-1", Pricing { input: 15.0, output: 75.0, cache_write: 18.75, cache_write_1h: 30.0, cache_read: 1.5 }),
    ("claude-opus-4-1-20250805", Pricing { input: 15.0, output: 75.0, cache_write: 18.75, cache_write_1h: 30.0, cache_read: 1.5 }),
    ("claude-opus-4-20250514", Pricing { input: 15.0, output: 75.0, cache_write: 18.75, cache_write_1h: 30.0, cache_read: 1.5 }),
    ("claude-opus-4-5", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-5-20251101", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-6", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-6-20260205", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-7", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-7-20260416", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-4-8", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-opus-5", Pricing { input: 5.0, output: 25.0, cache_write: 6.25, cache_write_1h: 10.0, cache_read: 0.5 }),
    ("claude-sonnet-4-20250514", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-sonnet-4-5", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-sonnet-4-5-20250929", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-sonnet-4-5-20250929-v1:0", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-sonnet-4-6", Pricing { input: 3.0, output: 15.0, cache_write: 3.75, cache_write_1h: 6.0, cache_read: 0.3 }),
    ("claude-sonnet-5", Pricing { input: 2.0, output: 10.0, cache_write: 2.5, cache_write_1h: 4.0, cache_read: 0.2 }),
];
